saruk_electronics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('APP_DB_HOST', 'postgres') }}"
      port: "{{ env_var('APP_DB_PORT', '5432') | int }}"
      dbname: "{{ env_var('APP_DB_NAME', 'saruk_db') }}"
      user: "{{ env_var('APP_DB_USER', 'postgres') }}"
      password: "{{ env_var('APP_DB_PASSWORD', 'postgres') }}"
      schema: public
      threads: 4
