apiVersion: 1
datasources:
  - name: Saruk PostgreSQL
    type: postgres
    url: postgres:5432
    database: saruk_db
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
